web:
    build: .
    working_dir: /go/src
    ports:
     - "5000:5000"
    volumes:
     - .:/go/src
    links:
     - db_redis
db_redis:
    hostname: db_redis 
    image: redis
    ports:
     - "6379:6379"
